[tasks.build]
install_crate = "wasm-pack"
command = "wasm-pack"
toolchain = "nightly"
args = [
    "build",
    "--out-dir",
    "../ts/src/ftml",
    "--out-name",
    "ftml",
    "--target",
    "web",
    "--",
    "--target",
    "wasm32-unknown-unknown",
    "-Z",
    "build-std=std,panic_abort,core,alloc",
    "-Z",
    "build-std-features=optimize_for_size", #,panic_immediate_abort",
    "--timings"
]

[tasks.clean-ts]
script_runner = "@shell"
script = '''
rm ../ts/src/ftml/.gitignore
rm ../ts/src/ftml/ftml_bg.wasm
rm ../ts/src/ftml/ftml_bg.wasm.d.ts
rm ../ts/src/ftml/package.json
'''


[tasks.default]
clear = true
dependencies = ["build","clean-ts"]
