import styles from "@/styles/Home.module.css";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
// import Test from "./test";
import { FTMLFragment, initialize } from "@flexiformal/ftml-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          [Fragment below]
          <FTMLFragment
            fragment={{
              type: "FromBackend",
              uri: "https://mathhub.info?a=courses/FAU/AI/course&p=course/sec&d=concept&l=en&e=section/paragraph",
            }}
          />
          [Fragment above]
          {/* <Test /> */}
        </main>
      </div>
    </>
  );
}
